### ISSUE TITLE
Where to find stm32l4xx-hal crate

### ISSUE THREAD

**Issue by esden** [gauteh/swan-stm32l4r5-quickstart#2]
Hi,

As far as I can see this example requires a version of [stm32l4xx-hal](https://github.com/gauteh/stm32l4xx-hal) crate with stm32l4r5 support. I don't seem to see a branch on your forked repository here that would contain support for it unless I am missing something. I just would like to know if I will need to work on that myself or not, it would be a shame to waste the effort. :)

Regards,
Piotr Esden-Tempski

**Comment by esden** [comment]
Sorry for the noise. It turns out there is an stm32l4r5 branch on your forked repository.

**Comment by gauteh** [comment]
Yes, two PRs submitted long time ago:

https://github.com/stm32-rs/stm32l4xx-hal/pull/292

and

https://github.com/stm32-rs/stm32l4xx-hal/pull/324

**Comment by esden** [comment]
It seems that the PAC is now there, and your patches need to be rebased ontop of the current master of the hal repo. The 292 PR is not passing CI checks and that needs to be fixed before it can be merged up stream.

**Comment by esden** [comment]
I see that the second PR is an updated version. I talked to the rust-embedded folks in their matrix channel. I got encouraged to try [embassy-stm32](https://crates.io/crates/embassy-stm32) instead as it already supports stm32l4r5 and it gets more work than stm32-rs at the moment. Thank you for your help :)

**Comment by gauteh** [comment]
Ok!
